---
title: "wc_prediction_22"
author: "Trent Meyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(here)
wc_matches_22 <- read_csv(here("data/wc_matches_22.csv"))
```

```{r}
wc_matches_full_22 <- wc_matches_22 %>% slice(1:48) %>% mutate(group = case_when(
  team1 == "Qatar" | team1 == "Ecuador" |
    team1 == "Senegal" | team1 == "Netherlands" ~ "A",
  
  team1 == "England" | team1 == "USA" |
    team1 == "Iran" | team1 == "Wales" ~ "B",
  
  team1 == "Argentina" | team1 == "Saudi Arabia" |
    team1 == "Mexico" | team1 == "Poland" ~ "C",
  
  team1 == "France" | team1 == "Australia" |
    team1 == "Denmark" | team1 == "Tunisia" ~ "D",
  
  team1 == "Spain" | team1 == "Germany" |
    team1 == "Japan" | team1 == "Costa Rica" ~ "E",
  
  team1 == "Belgium" | team1 == "Canada" |
    team1 == "Morocco" | team1 == "Croatia" ~ "F",
  
  team1 == "Brazil" | team1 == "Serbia" |
    team1 == "Switzerland" | team1 == "Cameroon" ~ "G",
  
  team1 == "Portugal" | team1 == "Ghana" |
    team1 == "Uruguay" | team1 == "South Korea" ~ "H"
)) %>%
  select(proj_score1, proj_score2, everything())
```

```{r}
predict_team1 <- function(proj_score1, proj_score2) {
  goals <- 0:10
  # predicting the probabilities that team1 will score 0:10 goals
  team1goals <- dpois(goals, proj_score1)

  # predicting the probabilities that team2 will score 0:10 goals
  team2goals <- dpois(goals, proj_score2)
  
  # Turning the probabilities into matrices
  team1goals_matrix <- matrix(team1goals, nrow = 1, ncol = 11)
  team2goals_matrix <- matrix(team2goals, nrow = 11, ncol = 1)
  
  # Multiplying the matrices to get an 11x11 matrix with probabilities
  # that each team will score that amount of goals, from which 
  # we can get the probability that each team will win
  goalsprobmatrix <- team2goals_matrix %*% team1goals_matrix
  
  # I transposed this because using as.vector went down the columns, except I wanted
  # to go across the rows first
  #goalsprobmatrix_t <- t(goalsprobmatrix)
  
  # With the transposed matrix, I wanted to create a vector, and then use cumsum()
  # to get the cumulative sum
  goalsprobvector <- as.vector(t(goalsprobmatrix), mode = "numeric")
  cumprobmatrix <- matrix(cumsum(goalsprobvector), nrow = 11, ncol = 11, byrow = TRUE)
  cumprob <- as.vector(t(cumprobmatrix), mode = "numeric")
  
  rowindices <- row(cumprobmatrix)
  rowvector <- as.vector(rowindices, mode = "numeric")

  colindices <- col(cumprobmatrix)
  colvector <- as.vector(colindices, mode = "numeric")

  probindextib <- tibble(rowvector, colvector, cumprob)

  # generate a random uniform value
  prob_index <- runif(1, 0, 1)
  
  # find out which values fall above that probability
  which_index <- which(cumprob >= prob_index)

  # single out the first index, and determine if that would be a win, loss, or draw,
  # and for which team
  index_sim <- which_index[1]
  
  probindextib <- probindextib %>% mutate(
    result = case_when(
      rowvector > colvector ~ "Team 1 Wins",
      rowvector == colvector ~ "Draw",
      rowvector < colvector ~ "Team 2 Wins"
    ),
    team1points = case_when(
      result == "Draw" ~ 1,
      result == "Team 1 Wins" ~ 3,
      result == "Team 2 Wins" ~ 0
    ),
    team2points = case_when(
      result == "Draw" ~ 1,
      result == "Team 2 Wins" ~ 3,
      result == "Team 1 Wins" ~ 0
    )
  ) 
  
  result_list <- c(probindextib$team1points[index_sim])
  
  # add in summing up the number of points for each team
  
  return(result_list)
}
```

```{r, cache=TRUE}
## expand slowly: predict the score for team 1 for every row of the data set:
## wrap in for loop and change 5 to i
niter <- 1000 ## so messing around with code takes less time
result_matrix_full_22 <- matrix(NA, nrow = nrow(wc_matches_full_22), ncol = niter)

set.seed(847267)
for (i in 1:nrow(wc_matches_full_22)) {
  result_matrix_full_22[i, ] <- map(1:niter, ~ predict_team1(proj_score1 = wc_matches_full_22 |> slice(i) |> pull(1),
              proj_score2 = wc_matches_full_22 |> slice(i) |> pull(2))) |>
  unlist()
  print(i)
}

#result_matrix_full_22
```

```{r}
wc_long_full_22 <- bind_cols(wc_matches_full_22, result_matrix_full_22) %>%
  select(-c(3:5, 8:20)) %>%
  pivot_longer(cols = starts_with("..."),
               names_to = "iteration",
               values_to = "team1points") %>%
  pivot_longer(cols = c(3, 4),
               names_to = "which_team",
               values_to = "team") %>%
  mutate(iteration = as.factor(iteration))
```

```{r}
wc_long_full_22 <- wc_long_full_22 %>% mutate(team1points = case_when(
  which_team == "team1" ~ team1points,
  which_team == "team2" & team1points == 3 ~ 0,
  which_team == "team2" & team1points == 0 ~ 3,
  which_team == "team2" & team1points == 1 ~ 1
))

wc_long_iter_full_22 <- wc_long_full_22 %>% group_by(iteration, team, group) %>% summarise(totalpoints = sum(team1points)) %>% arrange(group, iteration, totalpoints)

wc_long_iter_full_22 <-
  wc_long_iter_full_22 %>% 
  group_by(group, iteration) %>%
  arrange(group, iteration, totalpoints) %>%
  mutate(
    rank = rank(desc(totalpoints), ties.method = "last"),
    went_through = if_else(rank < 3,
                           true = 1,
                           false = 0)
    )

wc_long_iter_total_22 <- wc_long_iter_full_22 %>% 
  group_by(team, went_through) %>% 
  filter(went_through == "1") %>%
  summarise(numtimes = sum(went_through),
            proptimes = numtimes / niter) %>%
  mutate(group = case_when(
  team == "Qatar" | team == "Ecuador" |
    team == "Senegal" | team == "Netherlands" ~ "A",
  
  team == "England" | team == "USA" |
    team == "Iran" | team == "Wales" ~ "B",
  
  team == "Argentina" | team == "Saudi Arabia" |
    team == "Mexico" | team == "Poland" ~ "C",
  
  team == "France" | team == "Australia" |
    team == "Denmark" | team == "Tunisia" ~ "D",
  
  team == "Spain" | team == "Germany" |
    team == "Japan" | team == "Costa Rica" ~ "E",
  
  team == "Belgium" | team == "Canada" |
    team == "Morocco" | team == "Croatia" ~ "F",
  
  team == "Brazil" | team == "Serbia" |
    team == "Switzerland" | team == "Cameroon" ~ "G",
  
  team == "Portugal" | team == "Ghana" |
    team == "Uruguay" | team == "South Korea" ~ "H"
))

actually_went_through <- c("Netherlands", "USA", "Argentina", "Australia",
                           "Japan", "Croatia", "Brazil", "South Korea", 
                           "England", "Senegal", "France", "Poland",
                           "Morocco", "Spain", "Portugal", "Switzerland")
```

```{r}
wc_long_22_through <- wc_long_iter_total_22 %>% filter(team %in% actually_went_through)

ggplot(data = wc_long_iter_total_22, aes(x = proptimes, y = fct_reorder(team, proptimes))) +
  geom_point() + 
  geom_segment(data = wc_long_iter_total_22, aes(x = 0, xend = proptimes, y = team, yend = team)) + 
  geom_segment(data = wc_long_22_through, aes(x = 0, xend = proptimes, y = team, yend = team), colour = "red") +
  geom_point(data = wc_long_22_through, aes(x = proptimes, y = team), colour = "red") +
  facet_wrap(~group, scales = "free_y") +
  theme_minimal(base_size = 17) +
  labs(y = "Team",
       x = "Probability Out of Group Stage",
       title = "2022 World Cup Group Stage Predictions")

ggsave("World_Cup_Plot.jpg")

save(wc_long_iter_total_22, file = "wc_long_iter_total_22.rda")


```


